server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: true
  resources: 
    static-locations: 
      classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/,
      ,classpath:/templates/*,classpath:/templates/user/**
